### ISSUE TITLE
Framework: Configuration issue for CUDA AT build

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#10586]
## Bug Report
@trilinos/framework 

### Description
Multiple autotester runs (e.g. PRs #10571, #10507) have a failing CUDA build. As far as I can tell, this is a configuration issue, not a cmake/build/test problem.
```
A) Generate the Trilinos Packages definition and depencencies XML file

TrilinosPRConfigurationBase.py:573 create_package_enables_file()> --- There was an issue generating packageEnables.cmake.
TrilinosPRConfigurationBase.py:574 create_package_enables_file()> --- The error code was: 1
TrilinosPRConfigurationBase.py:575 create_package_enables_file()> --- Console Output:
None
Traceback (most recent call last):
File "/vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/_cuda_10.1.243/Trilinos/packages/framework/pr_tools/PullRequestLinuxDriverTest.py", line 310, in 
status = main(args)
File "/vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/_cuda_10.1.243/Trilinos/packages/framework/pr_tools/PullRequestLinuxDriverTest.py", line 298, in main
pr_config.prepare_test()
File "/vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/_cuda_10.1.243/Trilinos/packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py", line 758, in prepare_test
self.create_package_enables_file(dryrun=self.args.dry_run)
File "/vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/_cuda_10.1.243/Trilinos/packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py", line 578, in create_package_enables_file
raise cpe
File "/vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/_cuda_10.1.243/Trilinos/packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py", line 570, in create_package_enables_file
subprocess.check_call(cmd)
File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/subprocess.py", line 347, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/_cuda_10.1.243/Trilinos/commonTools/framework/get-changed-trilinos-packages.sh', 'origin/develop', 'HEAD', 'packageEnables.cmake', 'package_subproject_list.cmake', '2>&1']' returned non-zero exit status 1.
PRDriver> Command failed with status: 1

Build step 'Execute shell' marked build as failure
Archiving artifacts
[Checks API] No suitable checks publisher found.
Finished: FAILURE
```

**Comment by cgcgcg** [comment]
Looks like this got fixed.
