### ISSUE TITLE
Python incorrectly finding MPI

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#11631]
```
[100%] Generating Teuchos.RCP.i
cd /work2/00434/eijkhout/trilinos/build-13-4-1-clx-oneapi-impi/packages/PyTrilinos/src && /scratch1/projects/compilers/oneapi_2021.4.0.3422/intelpython/python3.7/bin/python3 /work2/00434/eijkhout/trilinos/build-13-4-1-clx-oneapi-impi/packages/PyTrilinos/src/gen_teuchos_rcp.py > /work2/00434/eijkhout/trilinos/build-13-4-1-clx-oneapi-impi/packages/PyTrilinos/src/Teuchos.RCP.i
Traceback (most recent call last):
  File "/work2/00434/eijkhout/trilinos/build-13-4-1-clx-oneapi-impi/packages/PyTrilinos/src/gen_teuchos_rcp.py", line 659, in <module>
    main()
  File "/work2/00434/eijkhout/trilinos/build-13-4-1-clx-oneapi-impi/packages/PyTrilinos/src/gen_teuchos_rcp.py", line 557, in main
    print("#define MPI_VERSION %s" % get_mpi_version())
  File "/work2/00434/eijkhout/trilinos/build-13-4-1-clx-oneapi-impi/packages/PyTrilinos/src/gen_teuchos_rcp.py", line 58, in get_mpi_version
    for line in open(header, 'r').readlines():
FileNotFoundError: [Errno 2] No such file or directory: '/intel64/include/mpi.h'
```

This looked like a truncated path, but I thought I was specifying everything.

Is this the explanation? `packages/PyTrilinos/src/gen_teuchos_rcp.py`:

```
# Find the MPI base directory
MPI_BASE_DIR   = "/intel64"
if WITH_MPI:
    if MPI_BASE_DIR == "":
        MPI_BIN_DIR  = os.path.split("")[0]
        MPI_BASE_DIR = os.path.split(MPI_BIN_DIR)[0]

################################################################################

def get_mpi_version():
    header = os.path.join(MPI_BASE_DIR, "include/mpi.h")
    version = ""
    for line in open(header, 'r').readlines():
        if "MPI_VERSION" in line:
            version = line.split()[2]
            break
    return version
```

**Comment by cgcgcg** [comment]
(I'm not a PyTrilinos developer.) This is what's in the source:
https://github.com/trilinos/Trilinos/blob/d5e2e9f17ae44b449f262ae4f3c599547e33885b/packages/PyTrilinos/src/gen_teuchos_rcp.py.in#L46-L47
Could you check what the CMake variable `MPI_BASE_DIR` is set to?
