### ISSUE TITLE
PyTrilinos: Revive PyTrilinos.Teuchos

### ISSUE THREAD

**Issue by wfspotz** [trilinos/Trilinos#3461]
@trilinos/pytrilinos 

## Expectations
I expect the `PyTrilinos.Teuchos` module to build and the related tests to pass.

## Current Behavior
All tests currently fail with the error message:

    Traceback (most recent call last):
      File "./testTeuchos.py", line 69, in <module>
        Teuchos = fromPyTrilinosImport('Teuchos', options.testharness, globals(), locals())
      File "/Development/Trilinos/PYTEUCHOS/packages/PyTrilinos/test/testutil.py", line 101, in fromPyTrilinosImport
        PyTrilinosPkg = __import__(fullname, globals, locals)
      File "/Development/Trilinos/PYTEUCHOS/packages/PyTrilinos/src/PyTrilinos/Teuchos/__init__.py", line 4370, in <module>
        class DefaultComm:
      File "/Development/Trilinos/PYTEUCHOS/packages/PyTrilinos/src/PyTrilinos/Teuchos/__init__.py", line 4372, in DefaultComm
        __defaultComm = MpiComm(mpiCommunicator)
      File "/Development/Trilinos/PYTEUCHOS/packages/PyTrilinos/src/PyTrilinos/Teuchos/__init__.py", line 4271, in __init__
        raise AttributeError("No constructor defined")
    AttributeError: No constructor defined

## Definition of Done
`PyTrilinos.Teuchos` builds and all PyTrilinos Teuchos tests pass.

## Possible Solution
Something changed with `DefaultComm` and the wrappers need to be updated to match.

**Comment by wfspotz** [comment]
Actually, these errors are only thrown when configuring with `mpi4py` active. This seems to be related to the following code snippet in `Teuchos_Comm.i`:

    #ifdef HAVE_MPI4PY
      MpiComm(MPI_Comm mpiComm = MPI_COMM_WORLD)
      {
        return new Teuchos::MpiComm< Ordinal >
          (Teuchos::opaqueWrapper(mpiComm));
      }
    #else
      MpiComm(PyObject * dummy = NULL)
      {
        return new Teuchos::MpiComm< Ordinal >
          (Teuchos::opaqueWrapper(MPI_COMM_WORLD));
      }
    #endif
