### ISSUE TITLE
Amesos2, MueLu issue with bad maps.

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#6002]
We are seeing an issue with maps in the latest trilinos update in Amesos2 

```
************ Caught Exception: End Error Report ************
/home/mbetten/Trilinos/Trilinos/packages/tpetra/core/src/Tpetra_Map_def.hpp:512:

Throw number = 1

Throw test that evaluated to true: numGlobalElements != GSTI && debugGlobalSum != numGlobalElements

Tpetra::Map constructor: The sum of each process' number of indices over all processes, 576 != numGlobalElements = 192.  If you would like this constructor to compute numGlobalElements for you, you may set numGlobalElements = Teuchos::OrdinalTraits<Tpetra::global_size_t>::invalid() on input.  Please note that this is NOT necessarily -1.

```

The traceback is here

```
#0  __cxxabiv1::__cxa_throw (obj=0x6934300, 
    tinfo=0x7fffc26bfa28 <typeinfo for std::invalid_argument>, 
    dest=0x7fffc23e32a0 <std::invalid_argument::~invalid_argument()>)
    at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:76
#1  0x00007fffcb4a1ceb in Tpetra::Map<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::initialNonuniformDebugCheck (this=0x681dfb0, numGlobalElements=192, numLocalElements=192, indexBase=0, 
    comm=...)
    at /home/mbetten/Trilinos/Trilinos/packages/tpetra/core/src/Tpetra_Map_def.hpp:504
#2  0x00007fffcb4a207c in Tpetra::Map<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::initWithNonownedHostIndexList (this=0x681dfb0, numGlobalElements=192, entryList_host=..., indexBase=0, 
    comm=...)
    at /home/mbetten/Trilinos/Trilinos/packages/tpetra/core/src/Tpetra_Map_def.hpp:575
#3  0x00007fffcb49c53b in Tpetra::Map<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Map (this=0x681dfb0, 
    numGlobalElements=192, entryList=..., indexBase=0, comm=..., 
    __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/mbetten/Trilinos/Trilinos/packages/tpetra/core/src/Tpetra_Map_def.hpp:873
#4  0x00007fffce87ce4f in Xpetra::TpetraMap<int, long long, Kokkos::Compat::Kok---Type <return> to continue, or q <return> to quit---
kosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::TpetraMap (
    this=0x67fa530, numGlobalElements=192, elementList=..., indexBase=0, 
    comm=..., __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Map/Xpetra_TpetraMap_def.hpp:134
#5  0x00007fffce8596f9 in Xpetra::MapFactory<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build (
    lib=Xpetra::UseTpetra, numGlobalElements=192, elementList=..., 
    indexBase=0, comm=...)
    at /home/mbetten/Trilinos/Trilinos/packages/xpetra/src/Map/Xpetra_MapFactory_def.hpp:183
#6  0x00007fffe3623301 in MueLu::Amesos2Smoother<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Setup
    (this=0x6874af0, currentLevel=...)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp:204
#7  0x00007fffe37e3bae in MueLu::DirectSolver<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Setup (
    this=0x68e90a0, currentLevel=...)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_DirectSolver_def.hpp:175
#8  0x00007fffe3b4f3b9 in MueLu::SmootherFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::BuildSm---Type <return> to continue, or q <return> to quit---
oother (this=0x68ec6f0, currentLevel=..., preOrPost=MueLu::BOTH)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherFactory_def.hpp:163
#9  0x00007fffe3b4f0bc in MueLu::SmootherFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build
    (this=0x68ec6f0, currentLevel=...)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Smoothers/MueLu_SmootherFactory_def.hpp:122
#10 0x00007fffe5131570 in MueLu::SingleLevelFactoryBase::CallBuild (
    this=0x68ec6f0, requestedLevel=...)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_SingleLevelFactoryBase.hpp:133
#11 0x00007fffe517933c in MueLu::Level::Get<Teuchos::RCP<MueLu::SmootherBase<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > > > (this=0x6932cf0, ename=..., factory=0x68ec6f0)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_Level.hpp:204
#12 0x00007fffe3c25dbd in MueLu::TopSmootherFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build (this=0x69da290, level=...)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/MueCentral/MueLu_TopSmootherFactory_def.hpp:98
#13 0x00007fffe389d35a in MueLu::Hierarchy<double, int, long long, Kokkos::Comp---Type <return> to continue, or q <return> to quit---
at::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Setup (
    this=0x68ab630, coarseLevelID=0, fineLevelManager=..., 
    coarseLevelManager=..., nextLevelManager=...)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp:483
#14 0x00007fffe49adfc7 in MueLu::HierarchyManager<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::SetupHierarchy (this=0x68b4730, H=...)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Interface/MueLu_HierarchyManager.hpp:241
#15 0x00007fffe495e55f in MueLu::ParameterListInterpreter<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::SetupHierarchy (this=0x68b4730, H=...)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp:2236
#16 0x00007fffeb2eadd6 in MueLu::CreateXpetraPreconditioner<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > (op=..., inParamList=...)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/adapters/xpetra/MueLu_CreateXpetraPreconditioner.hpp:97
#17 0x00007fffe514b782 in MueLu::RefMaxwell<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::compute (
    this=0x67ab420, reuse=false)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp:827
#18 0x00007fffe515feb1 in MueLu::RefMaxwell<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::resetMatrix
    (this=0x67ab420, SM_Matrix_new=..., ComputePrec=true)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp:1732
#19 0x00007fffeb2e9530 in MueLu::RefMaxwell<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::RefMaxwell
    (this=0x67ab420, SM_Matrix=..., List=..., ComputePrec=true, 
    __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp:286
#20 0x00007fffeb2dda24 in Thyra::MueLuRefMaxwellPreconditionerFactory<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::initializePrec (this=0x6697740, fwdOpSrc=..., prec=0x65969c0, 
    supportSolveUse=Thyra::SUPPORT_SOLVE_UNSPECIFIED)
    at /home/mbetten/Trilinos/Trilinos/packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_def.hpp:329
#21 0x00007fffdc052edb in Thyra::BelosLinearOpWithSolveFactory<double>::initializeOpImpl (this=0x6663620, fwdOpSrc=..., approxFwdOpSrc=..., prec_in=..., 
    reusePrec=false, Op=0x65be120, 

```

I've gone back to this commit and it still exists.
8854e7f2e148b87a6a2264cf33d18c20f5c3bb96

This is showing up in EMPIRE if you enable trilinos debug 

This is blocking EMPIRE's Trilinos promotion.  We can go over how to reproduce on SNL resources.

@krcb @bartlettroscoe @jhux2 @srajama1 @kddevin

**Comment by bartlettroscoe** [comment]
@bathmatt, what build and machine is this on?

**Comment by bathmatt** [comment]
debug, rhel7 sems

**Comment by bartlettroscoe** [comment]
@bathmat said:

> debug, rhel7 sems

What is the exact build name?  Is this a CUDA build or some other build?

FYI: Looks like all of our 'sems-rhel7' ATDM Trilinos builds supporting EMPIRE and GEMMA are down last 2 says due to git clone errors (shown on Jenkins).  (Will look into that in a separate JIRA issue.)  Therefore, if this is a defect that would have broken any Trilinos tests we would not have seen them.

**Comment by bathmatt** [comment]
-dir-gnu-debug-openmp-shared

This is older than that and it isn't tested in trilinos testing

**Comment by bathmatt** [comment]
I have it bracketed, I'm bisecting

**Comment by bartlettroscoe** [comment]
@bathmatt said:

> -dir-gnu-debug-openmp-shared
>
> it isn't tested in trilinos testing

What is 'dir'?  Why are we not testing this configuration?  What is different about this than what we are testing?

**Comment by bathmatt** [comment]
@cgcgcg looks like we're still not valid.  
If you build debug and run 
EMWaveInPlasma3DNoProjection-mpi-parallel
you'll see the error
```
commit 9b99b597e307ad6e1f689b2bba9a75ae661fdef4
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Fri Sep 6 14:22:01 2019 -0600

    MueLu RefMaxwell: Apply nullspace fix when no BCs are detected

:040000 040000 bc225310fb94a00ba68e4de33f60045acb7f3210 ad6b412e0cd5ba42d0ddf3f04dd3393bac66a071 M      packages
```

**Comment by cgcgcg** [comment]
@bathmatt Ah dang, there are still issues with this change? Will investigate.

**Comment by bartlettroscoe** [comment]
As discussed at the ATDM PI meeting today, it would be desirable to add a test to the native Trilinos test suite to expose this build before it is fixed so that we can ensure a related bug does not come back again.  In fact, such a test would have likely blocked the merge to 'develop' due to such a test failing in one of the PR builds.

**Comment by cgcgcg** [comment]
@bartlettroscoe This behavior should be tested by MueLu's Maxwell test. I'll have to figure out how this slipped through..

**Comment by bathmatt** [comment]
Only happens in parallel, are you testing mpi?

**Comment by bathmatt** [comment]
@cgcgcg once you get a patch let me know, I'll test it.
