### ISSUE TITLE
MueLu: Hanging in empire tests.

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#6392]
## Bug Report
@trilinos/muelu @cgcgcg @csiefer2 @jmgate @bathmatt 

### Description
The update of EMPIRE's fork of Trilinos has been broken for some time. Using today's trilinos development branch, we are seeing a hang in muelu in some empire tests. Stack trace is below. On a 4 process problem, mpi processes 0, 2, and 3 hang here:
```
(gdb) bt
#0  0x00007f2a1f9685de in mca_btl_vader_component_progress () from /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/lib/openmpi/mca_btl_vader.so
#1  0x00007f2a29a49dba in opal_progress () from /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/lib/libopen-pal.so.13
#2  0x00007f2a2d1ef8d5 in ompi_request_default_wait_all () from /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/lib/libmpi.so.12
#3  0x00007f2a2d21d1a1 in PMPI_Waitall () from /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/lib/libmpi.so.12
#4  0x0000000001cdd117 in Teuchos::MpiComm<int>::waitAll(Teuchos::ArrayView<Teuchos::RCP<Teuchos::CommRequest<int> > > const&) const ()
#5  0x000000000561f93c in Tpetra::Distributor::doWaits() ()
#6  0x0000000005b2b6eb in Tpetra::DistObject<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::doTransferNew(Tpetra::SrcDistObject const&, Tpetra::CombineMode, unsigned long, Kokkos::DualView<int const*, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void, void> const&, Kokkos::DualView<int const*, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void, void> const&, Kokkos::DualView<int const*, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void, void> const&, Kokkos::DualView<int const*, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void, void> const&, Tpetra::Distributor&, Tpetra::DistObject<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::ReverseOption, bool, bool) ()
#7  0x0000000005b20e0b in Tpetra::DistObject<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::doTransfer(Tpetra::SrcDistObject const&, Tpetra::Details::Transfer<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > const&, char const*, Tpetra::DistObject<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::ReverseOption, Tpetra::CombineMode, bool) ()
#8  0x0000000005b1e0ce in Tpetra::DistObject<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::doExport(Tpetra::SrcDistObject const&, Tpetra::Import<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > const&, Tpetra::CombineMode, bool) ()
#9  0x000000000538f515 in Xpetra::TpetraMultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::doExport(Xpetra::DistObject<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > const&, Xpetra::Import<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > const&, Xpetra::CombineMode) ()
#10 0x0000000003a2a48b in MueLu::RefMaxwell<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::applyInverseAdditive(Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > const&, Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >&) const ()
#11 0x0000000003a28334 in MueLu::RefMaxwell<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::apply(Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> > const&, Xpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >&, Teuchos::ETransp, double, double) const ()
#12 0x00000000030b4fb7 in Thyra::XpetraLinearOp<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::applyImpl(Thyra::EOpTransp, Thyra::MultiVectorBase<double> const&, Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, double, double) const ()
#13 0x0000000004864a3b in Belos::CGIter<double, Thyra::MultiVectorBase<double>, Thyra::LinearOpBase<double> >::initializeCG(Belos::CGIterationState<double, Thyra::MultiVectorBase<double> >&) ()
#14 0x00000000048754f4 in Belos::PseudoBlockCGSolMgr<double, Thyra::MultiVectorBase<double>, Thyra::LinearOpBase<double>, true>::solve() ()
#15 0x00000000048f4d93 in Thyra::BelosLinearOpWithSolve<double>::solveImpl(Thyra::EOpTransp, Thyra::MultiVectorBase<double> const&, Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, Teuchos::Ptr<Thyra::SolveCriteria<double> const>) const ()
#16 0x0000000002acc46f in empire::ElectroMagneticSolverInterface::applyJacobianInverse(Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, Thyra::MultiVectorBase<double> const&) const ()
#17 0x0000000002acbd8a in empire::ElectroMagneticSolverInterface::solveSystem() ()
#18 0x0000000001e7ea17 in empire::TimeStepExplicit<empire::MeshTraits<shards::Hexahedron<8u>, 1> >::takeStep(empire::utils::TimeStamp) ()
#19 0x0000000001c953f2 in void meshSpecificMain<empire::MeshTraits<shards::Hexahedron<8u>, 1> >(Teuchos::RCP<Teuchos::StackedTimer>&, Teuchos::RCP<Teuchos::MpiComm<int> const> const&, double, MainPicParameterLists&, bool, empire::MeshContainer&, empire::utils::TimeStamp&) ()
#20 0x0000000001c5b24d in main ()
(gdb) q
```
while process 1 seems to skips the call entirely and proceeds to the next collective in destructors at the end of the program. There is no output of warnings or errors. Maybe the wrong communicator is being used? 
```
(gdb) bt
#0  0x00007f43c8d648d0 in ompi_request_default_wait_all () from /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/lib/libmpi.so.12
#1  0x00007f43b9ea4de0 in ompi_coll_tuned_allreduce_intra_recursivedoubling () from /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/lib/openmpi/mca_coll_tuned.so
#2  0x00007f43c8d755d3 in PMPI_Allreduce () from /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/lib/libmpi.so.12
#3  0x00007f438fc6008e in mca_io_romio_dist_MPI_File_set_size () from /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/lib/openmpi/mca_io_romio.so
#4  0x00007f43c8d98c5f in PMPI_File_set_size () from /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.9.0/openmpi/1.10.1/lib/libmpi.so.12
#5  0x00007f43caaf548e in H5FD_mpio_truncate () from /projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.8.12/clang/3.9.0/openmpi/1.10.1/parallel/lib/libhdf5.so.8
#6  0x00007f43caaec190 in H5FD_truncate () from /projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.8.12/clang/3.9.0/openmpi/1.10.1/parallel/lib/libhdf5.so.8
#7  0x00007f43caada2f7 in H5F_dest () from /projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.8.12/clang/3.9.0/openmpi/1.10.1/parallel/lib/libhdf5.so.8
#8  0x00007f43caadb043 in H5F_try_close () from /projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.8.12/clang/3.9.0/openmpi/1.10.1/parallel/lib/libhdf5.so.8
#9  0x00007f43caada973 in H5F_close () from /projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.8.12/clang/3.9.0/openmpi/1.10.1/parallel/lib/libhdf5.so.8
#10 0x00007f43cab4931a in H5I_dec_ref () from /projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.8.12/clang/3.9.0/openmpi/1.10.1/parallel/lib/libhdf5.so.8
#11 0x00007f43cab4904f in H5I_dec_app_ref () from /projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.8.12/clang/3.9.0/openmpi/1.10.1/parallel/lib/libhdf5.so.8
#12 0x00007f43caadbb01 in H5Fclose () from /projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.8.12/clang/3.9.0/openmpi/1.10.1/parallel/lib/libhdf5.so.8
#13 0x0000000002ceccab in hdf5_close_file ()
#14 0x0000000002cecc51 in h5_close_file ()
#15 0x0000000001f8984f in empire::pic::ParticleDumpHDF5::~ParticleDumpHDF5() ()
#16 0x0000000001f892e1 in empire::pic::ParticleDump::~ParticleDump() ()
#17 0x0000000001d7cd0f in Teuchos::RCPNodeTmpl<empire::pic::ParticleDump, Teuchos::DeallocDelete<empire::pic::ParticleDump> >::delete_obj() ()
#18 0x0000000001e684e6 in empire::MeshAndParticleDump<empire::MeshTraits<shards::Hexahedron<8u>, 1> >::~MeshAndParticleDump() ()
#19 0x0000000001c98654 in void meshSpecificMain<empire::MeshTraits<shards::Hexahedron<8u>, 1> >(Teuchos::RCP<Teuchos::StackedTimer>&, Teuchos::RCP<Teuchos::MpiComm<int> const> const&, double, MainPicParameterLists&, bool, empire::MeshContainer&, empire::utils::TimeStamp&) ()
#20 0x0000000001c5b24d in main ()
```

### Steps to Reproduce
Build empire and run the test "EMPIRE-PIC:Regression:StaticBField-mpi-parallel"

**Comment by cgcgcg** [comment]
I can reproduce this. It looks like this is another incarnation of the singular matrix solve bug. The matrix only lives on one rank, which might explain the odd behavior. I am trying to understand why the matrix ends up being singular and why the nullspace fix is not kicking in.

**Comment by jmgate** [comment]
@cgcgcg, do you have an idea yet if this fix will be on the order of a day, week, month?  Depending on your intuition here, I might need to start messing around with EMPIRE's copy of Trilinos so we can get some Tempus changes in.

**Comment by cgcgcg** [comment]
@jmgate If it's just a matter of getting the test to pass, we could get away with modifying the size of the problem slightly, which makes the solve go through. This however relies on the fact that Amesos2 sometimes manages to solve a singular problem. It would be helpful to know what changes to Trilinos/EMPIRE actually made this test fail. I have to look into this some more before I can give a definitive time estimate, but it might not take longer than a week.

**Comment by cgcgcg** [comment]
@jmgate How much time do you think I have before you need to start messing with EMPIRE's Trilinos?

**Comment by jmgate** [comment]
I won't start monkeying with anything till Monday morning at the earliest.  I wouldn't recommend changing the problem size just to make the test pass, but maybe @bathmatt or @rppawlo has a different opinion there.

**Comment by rppawlo** [comment]
We really need to understand this. We are seeing a hang on astra for the L1 runs as well - looks to be the same code based on screen output (although I haven't done a stack trace there yet to verify).

**Comment by bathmatt** [comment]
Can I get an estimate of the timeline on this and the status?  Idealy a PM to my snl address
Thanks
Matt

**Comment by cgcgcg** [comment]
https://github.com/trilinos/Trilinos/pull/6405 should take care of this.

**Comment by bathmatt** [comment]
I'm testing currently with EMPIRE.
Thanks

**Comment by rppawlo** [comment]
Thanks @cgcgcg and @brian-kelley ! That fixed it. Closing.
