### ISSUE TITLE
TeuchosCore_show_stack test failing in new ATDM Trilinos 'ats2' debug builds

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#6821]
CC: @trilinos/teuchos

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label "impacting: tests"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-01-13&end=2020-02-11&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats2&field2=buildname&compare2=66&value2=dbg&field3=testname&compare3=61&value3=TeuchosCore_show_stack&field4=site&compare4=61&value4=vortex) the test:

* `TeuchosCore_show_stack`

in the new debug builds:

* `Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg`
* `Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg`

are failing showing:

```
================================================================================

TEST_0

Running: "/usr/tce/packages/spectrum-mpi/spectrum-mpi-2019.06.24-gcc-7.3.1/bin/mpiexec" "-np" "1" "-disable_gpu_hooks" "-map-by" "socket:PE=4" "/vscratch1/jenkins/vortex-slave/workspace/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg/SRC_AND_BUILD/BUILD/packages/teuchos/core/example/show_stack/TeuchosCore_show_stack.exe"

--------------------------------------------------------------------------------

Traceback (most recent call last):
  File unknown, in __libc_start_main()
  File "libc-start.c", line 0, in generic_start_main.isra.0()
  File "/vscratch1/jenkins/vortex-slave/workspace/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg/SRC_AND_BUILD/Trilinos/packages/teuchos/core/example/show_stack/cxx_main.cpp", line 66, in main()
    f();
  File "/vscratch1/jenkins/vortex-slave/workspace/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg/SRC_AND_BUILD/Trilinos/packages/teuchos/core/example/show_stack/cxx_main.cpp", line 57, in f()
    g();
  File "/vscratch1/jenkins/vortex-slave/workspace/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg/SRC_AND_BUILD/Trilinos/packages/teuchos/core/example/show_stack/cxx_main.cpp", line 50, in g()
    Teuchos::show_stacktrace();

Segfault caught. Printing stacktrace:

Traceback (most recent call last):
  File unknown, in __libc_start_main()
  File "libc-start.c", line 0, in generic_start_main.isra.0()
  File "/vscratch1/jenkins/vortex-slave/workspace/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg/SRC_AND_BUILD/Trilinos/packages/teuchos/core/example/show_stack/cxx_main.cpp", line 66, in main()
    f();
  File unknown, address: 0x1240
  File "/vscratch1/jenkins/vortex-slave/workspace/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg/SRC_AND_BUILD/Trilinos/packages/teuchos/core/src/Teuchos_stacktrace.cpp", line 439, in (anonymous namespace)::loc_segfault_callback_print_stack(int)
    Teuchos::show_stacktrace();

Done. Exiting the program.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node vortex53 exited on signal 6 (Aborted).
--------------------------------------------------------------------------

--------------------------------------------------------------------------------

TEST_0: Return code = 134
TEST_0: Pass criteria = Match REGEX {Traceback .most recent call last.:} [PASSED]
TEST_0: Pass criteria = Match REGEX {Segfault caught. Printing stacktrace:} [PASSED]
TEST_0: Pass criteria = Match REGEX {Done. Exiting the program.} [PASSED]
TEST_0: Pass criteria = Match REGEX {Teuchos::show_stacktrace()} [PASSED]
TEST_0: Pass criteria = Match REGEX {teuchos/core/example/show_stack/cxx_main.cpp., line 66, in main()} [PASSED]
TEST_0: Pass criteria = Match REGEX {f()} [PASSED]
TEST_0: Pass criteria = Match REGEX {teuchos/core/example/show_stack/cxx_main.cpp., line 57, in f()} [PASSED]
TEST_0: Pass criteria = Match REGEX {g()} [PASSED]
TEST_0: Pass criteria = Match REGEX {teuchos/core/example/show_stack/cxx_main.cpp., line 50, in g()} [PASSED]
TEST_0: Pass criteria = Match REGEX {char .p = NULL. .p = 0} [FAILED]
TEST_0: Result = FAILED
```

The problem seems to be that BinUtils and/or the name demangling code in Teuchos on this system are just not working.

## Current Status on CDash

* [Status of this test in these builds over last 5 days](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=5%20days%20ago&end=now&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats2&field2=buildname&compare2=66&value2=dbg&field3=testname&compare3=61&value3=TeuchosCore_show_stack&field4=site&compare4=61&value4=vortex)

## Steps to Reproduce

One should be able to reproduce this failure on the machine 'vortex' for the system 'ats2' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

ToDo: We need to provide instructions for 'ats2' env.

The exact commands to reproduce on 'vortex' loging node should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Teuchos=ON \
 $TRILINOS_DIR

$ make NP=16

$ ctest -R TeuchosCore_show_stack
```

**Comment by bartlettroscoe** [comment]
This is a nice feature to have when you are trying to debug something like a segfault to have a stacktrack with nice details like a debugger would give you.  However, I don't know it is worth the time to fight with the BinUtils and/or the Teuchos code that uses BinUtils on this system to fix this issue.  Therefore, I have added the `ATDM Env Issue` label and I am going to disable this test in debug 'ats2' builds for the time being to get this off of our plate.

**Comment by bartlettroscoe** [comment]
I disabled this test in these builds in PR #6822 merged on 2020-02-12 and as shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-02-01&end=2020-02-20&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-ats2&field2=buildname&compare2=66&value2=dbg&field3=testname&compare3=61&value3=TeuchosCore_show_stack&field4=site&compare4=61&value4=vortex) these tests have not show up in these builds since 2020-02-12.

I am going to close this as "wont" fix and set "Disabled Tests".  If someone wants stack trackes on this platform, we can open a new issue to work on that.
