### ISSUE TITLE
PyTrilinos: tests failed for missing __init__.py

### ISSUE THREAD

**Issue by sagitter** [trilinos/Trilinos#880]
Hi all.

A couple of `PyTrilinos` tests (`PyTrilinos_testIsorropia, PyTrilinos_testNOX_StatusTest`) are failing for missing `__init__.py` files:

```
        Start 1571: PyTrilinos_testNOX_StatusTest
1571: Test command: /usr/bin/python2.7 "testNOX_StatusTest.py" "--testharness"
1571: Test timeout computed to be: 2000
1571: Traceback (most recent call last):
1571:   File "testNOX_StatusTest.py", line 68, in <module>
1571:     NOX    = fromPyTrilinosImport('NOX'   , options.testharness)
1571:   File "/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build/packages/PyTrilinos/test/testutil.py", line 100, in fromPyTrilinosImport
1571:     PyTrilinosPkg = __import__(fullname, globals, locals)
1571:   File "/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build/packages/PyTrilinos/src/PyTrilinos/NOX/__init__.py", line 49, in <module>
1571:     ___init__ = swig_import_helper()
1571:   File "/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build/packages/PyTrilinos/src/PyTrilinos/NOX/__init__.py", line 48, in swig_import_helper
1571:     return importlib.import_module('___init__')
1571:   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
1571:     __import__(name)
1571: ImportError: No module named ___init__
1568/1571 Test #1570: PyTrilinos_testML_Preconditioner .............................................   Passed    0.31 sec
1569/1571 Test #1569: PyTrilinos_testML_PyMatrix ...................................................   Passed    0.31 sec
1570/1571 Test #1571: PyTrilinos_testNOX_StatusTest ................................................***Failed  Required regular expression not found.Regex=[End Result: TEST PASSED
]  0.13 sec

        Start 1557: PyTrilinos_testIsorropia
1557: Test command: /usr/bin/python2.7 "testIsorropia.py" "--testharness"
1557: Test timeout computed to be: 2000
1557: Traceback (most recent call last):
1557:   File "testIsorropia.py", line 55, in <module>
1557:     Isorropia   = fromPyTrilinosImport('Isorropia'  , True)
1557:   File "/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build/packages/PyTrilinos/test/testutil.py", line 100, in fromPyTrilinosImport
1557:     PyTrilinosPkg = __import__(fullname, globals, locals)
1557:   File "/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build/packages/PyTrilinos/src/PyTrilinos/Isorropia/__init__.py", line 32, in <module>
1557:     ___init__ = swig_import_helper()
1557:   File "/builddir/build/BUILD/trilinos-12.8.1/Trilinos-trilinos-release-12-8-1/build/packages/PyTrilinos/src/PyTrilinos/Isorropia/__init__.py", line 31, in swig_import_helper
1557:     return importlib.import_module('___init__')
1557:   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
1557:     __import__(name)
1557: ImportError: No module named ___init__
1554/1571 Test #1557: PyTrilinos_testIsorropia .....................................................***Failed  Required regular expression not found.Regex=[End Result: TEST PASSED
```

Build log: https://kojipkgs.fedoraproject.org//work/tasks/264/16560264/build.log

**Comment by wfspotz** [comment]
When I see this kind of error, it usually indicates some kind of corruption of the build system. This looks like an automated build. Is there any chance it was built on top of an earlier failed attempt?

**Comment by sagitter** [comment]
No but i have added Python shebang (`#!/usr/bin/python2.7`) on top of the file.

**Comment by wfspotz** [comment]
@sagitter, you added the shebang to which file?

**Comment by sagitter** [comment]
Ah, sorry; i have replaced `#!/usr/bin/env python` with `#!/usr/bin/python2.7` on all *.py installed files including `__init__.py`.

**Comment by wfspotz** [comment]
On a PyTrilinos installation I just built based on the most current develop branch, I only find one .py file that uses the shebang, and that is `PyTrilinos/__init__.py`. It uses the `PYTHON_EXECUTABLE` from cmake, and not `#! /usr/bin/env python`. So I don't understand where the shebangs you are replacing are coming from.

**Comment by sagitter** [comment]
I have removed `#!/usr/bin/env python` replacing. However, i noted that these failures happen on `fedora 26`, not on `fedora 24` and on `rhel7`.

And then, why does not find `___init__` module?

`1557: ImportError: No module named ___init__`

**Comment by mhoemmen** [comment]
btw nearly all of us are away for the Thanksgiving holiday starting today.  Most of us should be back to work Monday.

**Comment by sagitter** [comment]
Could be this issue related to new `CMake-3.7.0` ?

**Comment by mhoemmen** [comment]
@sagitter wrote:
> Could be this issue related to new CMake-3.7.0 ?

It's possible.  I'm not sure what @wfspotz uses for PyTrilinos testing, but most of us test with CMake versions between 2.8.11 (minimum version for building Trilinos) and 3.5.x.  I use 3.3.2 (3.4 had a performance regression).

**Comment by wfspotz** [comment]
Looks like I am using cmake 3.6.0, without problem.

Do you have LOCA enabled? The reason I ask is because this `___init__` module issue is only going to show up for those packages that have nested namespaces: NOX, LOCA, and Isorropia. If I understand things correctly, this is the _only_ issue were are addressing here, correct?

**Comment by sagitter** [comment]
All packages are enabled except `STK` and `gtest`.
`Trilinos` configuration from build in question: https://paste.fedoraproject.org/492076/

**Comment by wfspotz** [comment]
I installed `cmake-3.7.0` and was able to successfully build and test PyTrilinos, with no `import ___init__` issues. I did this on Mac OS X 10.11.6. So the `cmake` version seems to be eliminated.

I think that `fedora 26` is the likely culprit. Can you look in your build directory and confirm the following files:
```
    BUILD/packages/PyTrilinos/src/PyTrilinos/Isorropia/___init__.so
    BUILD/packages/PyTrilinos/src/PyTrilinos/NOX/___init__.so
```
I may have the suffix wrong -- it could be `.dyld` or something else on Fedora. But you are looking for dynamic libraries or shared objects.

**Comment by sagitter** [comment]
Are there:

```
$ cat build.log | grep Isorropia/___init__.so
[ 91%] Linking CXX shared module PyTrilinos/Isorropia/___init__.so
/usr/bin/c++  -fPIC   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fPIC -DNDEBUG -std=c++11 -fopenmp -O3 -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fPIC -Wl,--as-needed -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fPIC -Wl,--as-needed -shared  -o PyTrilinos/Isorropia/___init__.so CMakeFiles/PyTrilinos_Isorropia___init__.dir/Isorropia.__init__PYTHON_wrap.cpp.o libpytrilinos.so.12.8.1 ../../nox/src-loca/src-thyra/liblocathyra.so.12.8.1 ../../nox/src-loca/src-epetra/liblocaepetra.so.12.8.1 ../../nox/src-loca/src-lapack/liblocalapack.so.12.8.1 ../../nox/src-loca/src/libloca.so.12.8.1 ../../nox/src-epetra/libnoxepetra.so.12.8.1 ../../nox/src-lapack/libnoxlapack.so.12.8.1 ../../nox/src/libnox.so.12.8.1 ../../teko/src/libteko.so.12.8.1 ../../ifpack2/adapters/libifpack2-adapters.so.12.8.1 ../../ifpack2/src/libifpack2.so.12.8.1 ../../zoltan2/src/libzoltan2.so.12.8.1 ../../amesos2/src/libamesos2.so.12.8.1 ../../stratimikos/src/libstratimikos.so.12.8.1 ../../stratimikos/adapters/belos/src/libstratimikosbelos.so.12.8.1 ../../stratimikos/adapters/aztecoo/src/libstratimikosaztecoo.so.12.8.1 ../../stratimikos/adapters/amesos/src/libstratimikosamesos.so.12.8.1 ../../stratimikos/adapters/ml/src/libstratimikosml.so.12.8.1 ../../stratimikos/adapters/ifpack/src/libstratimikosifpack.so.12.8.1 ../../anasazi/tpetra/src/libanasazitpetra.so.12.8.1 ../../anasazi/epetra/util/ModeLaplace/libModeLaplace.so.12.8.1 ../../anasazi/epetra/src/libanasaziepetra.so.12.8.1 ../../anasazi/src/libanasazi.so.12.8.1 ../../belos/tpetra/src/libbelostpetra.so.12.8.1 ../../belos/epetra/src/libbelosepetra.so.12.8.1 ../../belos/src/libbelos.so.12.8.1 ../../komplex/src/libkomplex.so.12.8.1 ../../ml/src/libml.so.12.8.1 ../../ifpack/src/libifpack.so.12.8.1 ../../amesos/src/libamesos.so.12.8.1 ../../galeri/src-xpetra/libgaleri-xpetra.so.12.8.1 ../../galeri/src-epetra/libgaleri-epetra.so.12.8.1 ../../xpetra/sup/libxpetra-sup.so.12.8.1 ../../xpetra/src/libxpetra.so.12.8.1 ../../thyra/adapters/epetraext/src/libthyraepetraext.so.12.8.1 ../../thyra/adapters/tpetra/src/libthyratpetra.so.12.8.1 ../../thyra/adapters/epetra/src/libthyraepetra.so.12.8.1 ../../thyra/core/src/libthyracore.so.12.8.1 ../../rtop/src/librtop.so.12.8.1 ../../aztecoo/src/libaztecoo.so.12.8.1 ../../pliris/src/libdpliris.so.12.8.1 ../../isorropia/src/libisorropia.so.12.8.1 ../../zoltan/src/libzoltan.so.12.8.1 -lm ../../zoltan/siMPI/pyMPI/siMPI/libsimpi.so.12.8.1 ../../epetraext/src/libepetraext.so.12.8.1 ../../tpetra/core/ext/libtpetraext.so.12.8.1 ../../tpetra/core/inout/libtpetrainout.so.12.8.1 ../../tpetra/core/src/libtpetra.so.12.8.1 ../../tpetra/tsqr/src/libkokkostsqr.so.12.8.1 ../../tpetra/kernels/src/libtpetrakernels.so.12.8.1 ../../kokkos/algorithms/src/libkokkosalgorithms.so.12.8.1 ../../kokkos/containers/src/libkokkoscontainers.so.12.8.1 ../../tpetra/classic/LinAlg/libtpetraclassiclinalg.so.12.8.1 ../../tpetra/classic/NodeAPI/libtpetraclassicnodeapi.so.12.8.1 ../../tpetra/classic/src/libtpetraclassic.so.12.8.1 ../../triutils/src/libtriutils.so.12.8.1 ../../epetra/src/libepetra.so.12.8.1 ../../teuchos/kokkoscomm/src/libteuchoskokkoscomm.so.12.8.1 ../../teuchos/kokkoscompat/src/libteuchoskokkoscompat.so.12.8.1 ../../teuchos/remainder/src/libteuchosremainder.so.12.8.1 ../../teuchos/numerics/src/libteuchosnumerics.so.12.8.1 /usr/lib64/liblapack.so /usr/lib64/libblas.so ../../teuchos/comm/src/libteuchoscomm.so.12.8.1 ../../teuchos/parameterlist/src/libteuchosparameterlist.so.12.8.1 ../../teuchos/core/src/libteuchoscore.so.12.8.1 ../../kokkos/core/src/libkokkoscore.so.12.8.1 
-- Installing: /builddir/build/BUILDROOT/trilinos-12.8.1-1.fc26.x86_64/usr/lib64/python2.7/site-packages/PyTrilinos/Isorropia/___init__.so
extracting debug info from /builddir/build/BUILDROOT/trilinos-12.8.1-1.fc26.x86_64/usr/lib64/python2.7/site-packages/PyTrilinos/Isorropia/___init__.so
```

```
$ cat build.log | grep PyTrilinos/NOX/___init__.so
[ 90%] Linking CXX shared module PyTrilinos/NOX/___init__.so
/usr/bin/c++  -fPIC   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fPIC -DNDEBUG -std=c++11 -fopenmp -O3 -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fPIC -Wl,--as-needed -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fPIC -Wl,--as-needed -shared  -o PyTrilinos/NOX/___init__.so CMakeFiles/PyTrilinos_NOX___init__.dir/NOX.__init__PYTHON_wrap.cpp.o libpytrilinos.so.12.8.1 ../../nox/src-loca/src-thyra/liblocathyra.so.12.8.1 ../../nox/src-loca/src-epetra/liblocaepetra.so.12.8.1 ../../nox/src-loca/src-lapack/liblocalapack.so.12.8.1 ../../nox/src-loca/src/libloca.so.12.8.1 ../../nox/src-epetra/libnoxepetra.so.12.8.1 ../../nox/src-lapack/libnoxlapack.so.12.8.1 ../../nox/src/libnox.so.12.8.1 ../../teko/src/libteko.so.12.8.1 ../../ifpack2/adapters/libifpack2-adapters.so.12.8.1 ../../ifpack2/src/libifpack2.so.12.8.1 ../../zoltan2/src/libzoltan2.so.12.8.1 ../../amesos2/src/libamesos2.so.12.8.1 ../../stratimikos/src/libstratimikos.so.12.8.1 ../../stratimikos/adapters/belos/src/libstratimikosbelos.so.12.8.1 ../../stratimikos/adapters/aztecoo/src/libstratimikosaztecoo.so.12.8.1 ../../stratimikos/adapters/amesos/src/libstratimikosamesos.so.12.8.1 ../../stratimikos/adapters/ml/src/libstratimikosml.so.12.8.1 ../../stratimikos/adapters/ifpack/src/libstratimikosifpack.so.12.8.1 ../../anasazi/tpetra/src/libanasazitpetra.so.12.8.1 ../../anasazi/epetra/util/ModeLaplace/libModeLaplace.so.12.8.1 ../../anasazi/epetra/src/libanasaziepetra.so.12.8.1 ../../anasazi/src/libanasazi.so.12.8.1 ../../belos/tpetra/src/libbelostpetra.so.12.8.1 ../../belos/epetra/src/libbelosepetra.so.12.8.1 ../../belos/src/libbelos.so.12.8.1 ../../komplex/src/libkomplex.so.12.8.1 ../../ml/src/libml.so.12.8.1 ../../ifpack/src/libifpack.so.12.8.1 ../../amesos/src/libamesos.so.12.8.1 ../../galeri/src-xpetra/libgaleri-xpetra.so.12.8.1 ../../galeri/src-epetra/libgaleri-epetra.so.12.8.1 ../../xpetra/sup/libxpetra-sup.so.12.8.1 ../../xpetra/src/libxpetra.so.12.8.1 ../../thyra/adapters/epetraext/src/libthyraepetraext.so.12.8.1 ../../thyra/adapters/tpetra/src/libthyratpetra.so.12.8.1 ../../thyra/adapters/epetra/src/libthyraepetra.so.12.8.1 ../../thyra/core/src/libthyracore.so.12.8.1 ../../rtop/src/librtop.so.12.8.1 ../../aztecoo/src/libaztecoo.so.12.8.1 ../../pliris/src/libdpliris.so.12.8.1 ../../isorropia/src/libisorropia.so.12.8.1 ../../zoltan/src/libzoltan.so.12.8.1 -lm ../../zoltan/siMPI/pyMPI/siMPI/libsimpi.so.12.8.1 ../../epetraext/src/libepetraext.so.12.8.1 ../../tpetra/core/ext/libtpetraext.so.12.8.1 ../../tpetra/core/inout/libtpetrainout.so.12.8.1 ../../tpetra/core/src/libtpetra.so.12.8.1 ../../tpetra/tsqr/src/libkokkostsqr.so.12.8.1 ../../tpetra/kernels/src/libtpetrakernels.so.12.8.1 ../../kokkos/algorithms/src/libkokkosalgorithms.so.12.8.1 ../../kokkos/containers/src/libkokkoscontainers.so.12.8.1 ../../tpetra/classic/LinAlg/libtpetraclassiclinalg.so.12.8.1 ../../tpetra/classic/NodeAPI/libtpetraclassicnodeapi.so.12.8.1 ../../tpetra/classic/src/libtpetraclassic.so.12.8.1 ../../triutils/src/libtriutils.so.12.8.1 ../../epetra/src/libepetra.so.12.8.1 ../../teuchos/kokkoscomm/src/libteuchoskokkoscomm.so.12.8.1 ../../teuchos/kokkoscompat/src/libteuchoskokkoscompat.so.12.8.1 ../../teuchos/remainder/src/libteuchosremainder.so.12.8.1 ../../teuchos/numerics/src/libteuchosnumerics.so.12.8.1 /usr/lib64/liblapack.so /usr/lib64/libblas.so ../../teuchos/comm/src/libteuchoscomm.so.12.8.1 ../../teuchos/parameterlist/src/libteuchosparameterlist.so.12.8.1 ../../teuchos/core/src/libteuchoscore.so.12.8.1 ../../kokkos/core/src/libkokkoscore.so.12.8.1 
-- Installing: /builddir/build/BUILDROOT/trilinos-12.8.1-1.fc26.x86_64/usr/lib64/python2.7/site-packages/PyTrilinos/NOX/___init__.so
extracting debug info from /builddir/build/BUILDROOT/trilinos-12.8.1-1.fc26.x86_64/usr/lib64/python2.7/site-packages/PyTrilinos/NOX/___init__.so
```

**Comment by wfspotz** [comment]
I'm running out of ideas. Now I'm looking at your python version. From your configuration file, you are picking up a python with version `2.7.12`. I am running `2.7.10`. It seems highly unlikely that a newer python would change the import rules such that this could happen. But you might try with `2.7.10` to see what happens.

Basically, we have imported, say, `NOX/__init__.py`, which in turn is trying to import `___init__`, which is a python extension (shared library) _in the same directory_ as the importing file. And we have verified that it is there.

**Comment by sagitter** [comment]
I guess i found a workaround: how happens with the libraries for testing, i had to set paths for finding  `__init__.py` files before running `ctest`:

```
export LD_LIBRARY_PATH=...
export PYTHONPATH=%{buildroot}%{python2_sitearch}/PyTrilinos:%{_builddir}/build/packages/PyTrilinos/src/PyTrilinos/Isorropia:%{_builddir}/build/packages/PyTrilinos/src/PyTrilinos/NOX
ctest -j4 --timeout 3000 -VV --force-new-ctest-process --output-on-failure
```

Just `PyTrilinos_testNOX_StatusTest` is failed but because different reason:

```
1606: Traceback (most recent call last):
1606:   File "testNOX_StatusTest.py", line 68, in <module>
1606:     NOX    = fromPyTrilinosImport('NOX'   , options.testharness)
1606:   File "/builddir/build/BUILD/trilinos-12.10.1/Trilinos-trilinos-release-12-10-1/build/packages/PyTrilinos/test/testutil.py", line 100, in fromPyTrilinosImport
1606:     PyTrilinosPkg = __import__(fullname, globals, locals)
1606:   File "/builddir/build/BUILD/trilinos-12.10.1/Trilinos-trilinos-release-12-10-1/build/packages/PyTrilinos/src/PyTrilinos/NOX/__init__.py", line 136, in <module>
1606:     class SwigPyIterator(_object):
1606:   File "/builddir/build/BUILD/trilinos-12.10.1/Trilinos-trilinos-release-12-10-1/build/packages/PyTrilinos/src/PyTrilinos/NOX/__init__.py", line 147, in SwigPyIterator
1606:     __swig_destroy__ = ___init__.delete_SwigPyIterator
1606: AttributeError: 'module' object has no attribute 'delete_SwigPyIterator'
1605/1606 Test #1606: PyTrilinos_testNOX_StatusTest ................................................***Failed  Required regular expression not found.Regex=[End Result: TEST PASSED
]  0.24 sec
Traceback (most recent call last):
  File "testNOX_StatusTest.py", line 68, in <module>
    NOX    = fromPyTrilinosImport('NOX'   , options.testharness)
  File "/builddir/build/BUILD/trilinos-12.10.1/Trilinos-trilinos-release-12-10-1/build/packages/PyTrilinos/test/testutil.py", line 100, in fromPyTrilinosImport
    PyTrilinosPkg = __import__(fullname, globals, locals)
  File "/builddir/build/BUILD/trilinos-12.10.1/Trilinos-trilinos-release-12-10-1/build/packages/PyTrilinos/src/PyTrilinos/NOX/__init__.py", line 136, in <module>
    class SwigPyIterator(_object):
  File "/builddir/build/BUILD/trilinos-12.10.1/Trilinos-trilinos-release-12-10-1/build/packages/PyTrilinos/src/PyTrilinos/NOX/__init__.py", line 147, in SwigPyIterator
    __swig_destroy__ = ___init__.delete_SwigPyIterator
AttributeError: 'module' object has no attribute 'delete_SwigPyIterator'
```

Build log: https://kojipkgs.fedoraproject.org//work/tasks/8553/16718553/build.log

**Comment by wfspotz** [comment]
@sagitter, because these errors occur on a very specific platform, I'd have to have access to the machine to have any hope of tracking this down.

**Comment by wfspotz** [comment]
What is your SWIG version?
