### ISSUE TITLE
Tpetra: recent PR is causing seg faults in Albany tests with clang compiler

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#9796]
The following PR caused Albany tests on CEE with a clang compiler to break: 
```
commit 1cb5bc6b9366977ecb143b7bcdcc5e1e94274f54
Merge: b0fff4b 0068a2f
Author: trilinos-autotester <trilinos@sandia.gov>
Date:   Tue Oct 5 14:43:34 2021 -0600
    Merge Pull Request #9616 from trilinos/Trilinos/csiefer-multivector-wrapped-dualview
    Automatically Merged using Trilinos Pull Request AutoTester
    PR Title: Tpetra: Reimplementation of MultiVector using WrappedDualView
    PR Author: csiefer2
```
Specifically, the tests are seg-faulting, as can be seen here: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=23682 .

Here is a backtrace on the error from GDB:

```
Program received signal SIGSEGV, Segmentation fault.
Kokkos::Impl::ViewDimension<0ul, 0ul>::extent (this=0x568, r=0)
    at /scratch/ikalash/albanyFPEs/TrilinosBad/build-clang-dbg/install/include/impl/Kokkos_ViewMapping.hpp:203
203	               ? N0
Missing separate debuginfos, use: debuginfo-install blas-3.4.2-8.el7.x86_64 cyrus-sasl-lib-2.1.26-23.el7.x86_64 glibc-2.17-292.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-37.el7_7.2.x86_64 lapack-3.4.2-8.el7.x86_64 libX11-1.6.7-2.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libcom_err-1.42.9-16.el7.x86_64 libcurl-7.29.0-54.el7_7.1.x86_64 libibverbs-22.1-3.el7.x86_64 libidn-1.28-4.el7.x86_64 libnl3-3.2.28-4.el7.x86_64 librdmacm-22.1-3.el7.x86_64 libselinux-2.5-14.1.el7.x86_64 libssh2-1.8.0-3.el7.x86_64 libxcb-1.13-1.el7.x86_64 nspr-4.21.0-1.el7.x86_64 nss-3.44.0-4.el7.x86_64 nss-softokn-freebl-3.44.0-5.el7.x86_64 nss-util-3.44.0-3.el7.x86_64 openldap-2.4.44-21.el7_6.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  Kokkos::Impl::ViewDimension<0ul, 0ul>::extent (this=0x568, r=0)
    at /scratch/ikalash/albanyFPEs/TrilinosBad/build-clang-dbg/install/include/impl/Kokkos_ViewMapping.hpp:203
#1  0x00007fffea0d48b8 in Kokkos::Impl::ViewMapping<Kokkos::ViewTraits<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >, void>::extent<int> (this=0x560, r=@0x7fffffff4784: 0)
    at /scratch/ikalash/albanyFPEs/TrilinosBad/build-clang-dbg/install/include/impl/Kokkos_ViewMapping.hpp:2989
#2  0x00007fffea0d31d4 in Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::extent<int> (
    this=0x558, r=@0x7fffffff4784: 0) at /scratch/ikalash/albanyFPEs/TrilinosBad/build-clang-dbg/install/include/Kokkos_View.hpp:659
#3  0x00007fffcb7288cb in Tpetra::Details::WrappedDualView<Kokkos::DualView<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void> >::extent (this=0x4b0, i=0)
    at /scratch/ikalash/albanyFPEs/TrilinosBad/packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp:202
#4  0x00007fffcb71608c in (anonymous namespace)::getDualViewStride<Tpetra::Details::WrappedDualView<Kokkos::DualView<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void> > > (dv=...)
    at /scratch/ikalash/albanyFPEs/TrilinosBad/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:328
#5  0x00007fffcb728ac4 in Tpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::MultiVector (this=0x7fffffff5a80, map=..., view=...)
    at /scratch/ikalash/albanyFPEs/TrilinosBad/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:552
#6  0x00007fffcb738cbb in Tpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::MultiVector (this=0xc607b0, X=..., subMap=..., rowOffset=0)
    at /scratch/ikalash/albanyFPEs/TrilinosBad/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:3394
#7  0x00007fffcba73793 in Tpetra::FEMultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::FEMultiVector (this=0x7fffffff73f0, map=..., importer=..., numVecs=1, zeroOut=true)
    at /scratch/ikalash/albanyFPEs/TrilinosBad/packages/tpetra/core/src/Tpetra_FEMultiVector_def.hpp:93
#8  0x00007fffea6c9da8 in Albany::ThyraCrsMatrixFactory::fillComplete (this=0xaa39c0)
    at /scratch/ikalash/albanyFPEs/Albany/src/utility/Albany_ThyraCrsMatrixFactory.cpp:209
#9  0x00007fffeadda059 in Albany::STKDiscretization::computeGraphs (this=0xa980c0)
    at /scratch/ikalash/albanyFPEs/Albany/src/disc/stk/Albany_STKDiscretization.cpp:1382
#10 0x00007fffeade5f8c in Albany::STKDiscretization::updateMesh (this=0xa980c0)
    at /scratch/ikalash/albanyFPEs/Albany/src/disc/stk/Albany_STKDiscretization.cpp:2512
#11 0x00007fffeac66496 in Albany::DiscretizationFactory::completeDiscSetup (this=0xa32e20, disc=...)
    at /scratch/ikalash/albanyFPEs/Albany/src/disc/Albany_DiscretizationFactory.cpp:300

#12 0x00007fffeac65c07 in Albany::DiscretizationFactory::createDiscretization (this=0xa32e20, neq=3, sideSetEquations=..., sis=..., 
    side_set_sis=..., req=..., side_set_req=..., rigidBodyModes=...)
    at /scratch/ikalash/albanyFPEs/Albany/src/disc/Albany_DiscretizationFactory.cpp:178
#13 0x00007fffea4e1a31 in Albany::Application::createDiscretization (this=0xa32640)
    at /scratch/ikalash/albanyFPEs/Albany/src/Albany_Application.cpp:583
#14 0x00007fffea4d920a in Albany::Application::Application (this=0xa32640, comm_=..., params=..., initial_guess=...)
    at /scratch/ikalash/albanyFPEs/Albany/src/Albany_Application.cpp:78
#15 0x00007fffea0475d0 in Albany::SolverFactory::createApplication (this=0x7fffffffb678, appComm=..., initial_guess=...)
    at /scratch/ikalash/albanyFPEs/Albany/src/Albany_SolverFactory.cpp:157
#16 0x00000000004576a8 in main (argc=2, argv=0x7fffffffb938) at /scratch/ikalash/albanyFPEs/Albany/src/Main_Solve.cpp:136
```
It looks like the code is dying on this fillComplete() in Albany: https://github.com/sandialabs/Albany/blob/master/src/disc/stk/Albany_STKDiscretization.cpp#L1382 , I'm not sure why.

@trilinos/tpetra

**Comment by jhux2** [comment]
@csiefer2
